### PR TITLE
Expose a type for PathSegment

### PR DESCRIPTION
**Pull request by mightybyte**
Here's an addition that exposes a standalone type for path segments.  I think this improves the ability to work with paths and partial paths.  There may be some missing interface functionality, but I'll let you decide how to handle the tradeoffs there with respect to backwards compatibility and API design preferences.

### CODE REVIEW

**Comment by domdere** [comment]
I'm going to marge this in but there are some issues with it i will have to fix before making a new cut for hackage:

1. The `segString` record has been exported, i'm going to remove this and replace it with a function `PathSegment -> String` as usage like this defeats the purpose of the `mkPathSegment` function and ruin the safety of the type:

``` Haskell
*Data.FilePath Data.Functor> (\c -> c {segString = "Lots'O'SlashesOhNoBroken!!//////////"}) <$> mkPathSegment "noSlashesOrControlCharsIsSafe"
Just (PathSegment {segString = "Lots'O'SlashesOhNoBroken!!//////////"})
```

2. Going to add a function to create FilePaths of the appropriate types from `PathSegment`, allowing you to get around a layer of `Maybe`, which to me seems like the point of the change.

3. I'll probably add a function `String -> PathSegment` function that filters the undesirable chars out of the input `String` and gets you a safe `PathSegment` allowing you to create safe constants where quasiquoters dont help. (The function would be the identity on valid strings)

for ex:

``` Haskell
import Date.Time.Format ( FormatTime, formatTime )
import System.Locale ( defaultTimeLocale )

-- Can't do this at the moment, but should be able to with this new PathSegment Type:
-- The output shouldn't have to be of type Maybe (FilePath ...), we know formatTime is going to produce
-- a String without invalid chars given the literal format string its been given.  Cant see how to do this with
-- QuasiQuoter though...
--
yearPath :: (FormatTime t) => t -> FilePath a Directory
yearPath = mkDirPath . formatTime defaultTimeLocale "year=%Y" 
```

**Comment by domdere** [comment]
`basenameSeg` and `segQ` were also missing from the export list, i'll fix that too

**Comment by domdere** [comment]
@mightybyte 

For 2. : It doesn't look like a `PathSegment -> FilePath Relative a` type function is currently possible as the `PathSegment` type does not certify that the null check on the string has taken place....

Please see #8. I have made `mkPathSegment` also run the null check, hence `PathSegment` certifies that all the checks have taken place, meaning we can safely have functions of type `PathSegment -> FilePath Relative a`.  

Please let me know if the exclusion of empty strings from `PathSegment` causes you any problems, I'll probably merge that change in sometime tomorrow if i dont hear any objections

(the empty string problem makes point 3. I made in the last comment irrelevant)

**Comment by mightybyte** [comment]
Yeah, all this makes sense to me.  I definitely agree that excluding empty strings from PathSegment seems like a much better thing to do now.  I don't think I had a good reason for going with Monoid except that Monoid is much more widely used.  My main use case was being able to prepend and append things to PathSegments for disambiguation, so you wouldn't want to use empty strings there anyway.

**Pull request merged**
